version: '3.4'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - syongjun-tore-network  # 두개의 이미지를 같은 네트워크를 사용하도록 세팅
  yongjun-store:
    image: yongjun-store
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:8081
    networks:
      - syongjun-tore-network  # 두개의 이미지를 같은 네트워크를 사용하도록 세팅
    depends_on:
      - redis

networks:
  my-network:
    driver: bridge