spring:
  spring:
    config:
      activate:
        on-profile: local

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true # 페이지를 1부터 시작 (default 0)
        default-page-size: 5 # 한 페이지 당 표시할 데이터 수

  datasource:
    url: jdbc:h2:mem:yongJunStore
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true


fileUpload:
  upload:
    local:
      path: 'src/main/resources/static'