spring:
  spring:
    config:
      activate:
        on-profile: prod


  data:
    web:
      pageable:
        one-indexed-parameters: true # 페이지를 1부터 시작 (default 0)
        default-page-size: 5 # 한 페이지 당 표시할 데이터 수


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://yongjun-rds-mysql8.cpowku6g4wpx.ap-northeast-2.rds.amazonaws.com:3306/yongjun-store
    username: admin
    password: admin!1234


  jpa:
    hibernate:
      ddl-auto: create
    database: mysql

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

backend-url: ${PROD_BACKEND_URL}
frontend-url: ${PROD_FRONTEND_URL}