spring:
  config:
    activate:
      on-profile: mysql

  data:
    web:
      pageable:
        default-page-size: 4 # 한 페이지의 값 개수
        max-page-size: 2000 # 최대 페이지 개수


    redis:
      host: ${LOCAL_URL}
      port: 6379

  devtools:
    restart:
      enabled: false


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${LOCAL_URL}:3306/yongjun-store
    username: ${USER_NAME}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        default_batch_fetch_size: 1000 # 메모리에서 작업 --> in(1, 2, 3 ...) 처리
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080


fileUpload:
  upload:
    local:
      path: 'src/main/resources/static'