spring:
  data:
    web:
      pageable:
        # default-page-size: 4 # 한 페이지의 값 개수
        max-page-size: 2000 # 최대 페이지 개수

  devtools:
    restart:
      enabled: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 941574435155-jipror8aqrh727oa6tuikqsbmaeij5i6.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: profile,email

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yongjun-store
    username: yongjun
    password: root


  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        default_batch_fetch_size: 1000 # 메모리에서 작업 --> in(1, 2, 3 ...) 처리
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

custom:
  jwt:
    secretKey: javaSpringBootProjectProtectedKimYongJunStoreJsonWebTokenSecretKey

fileUpload:
  upload:
    local:
      path: 'src/main/resources/static'